version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: "Rise ssh port forwarding"
          command: |
            echo "${PROXY_PRIVATE_KEY}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh -o "StrictHostKeyChecking no" -fNT -L 34323:${IP}:34323 circleci@${PROXY_IP} -i ~/.ssh/id_ed25519
      - run:
          name: "Run tests and collect coverage reports"
          command: |
            go mod vendor
            go test ./... -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
            mv c.out /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - codecov/upload:
          file: /tmp/artifacts/*