version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: "Create directories"
          command: |
            mkdir -p /tmp/artifacts
            mkdir ~/.ssh
      - run:
          name: "Rise ssh port forwarding connection"
          command: |
            echo ${PROXY_PRIVATE_KEY} | base64 --decode > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/*
            ssh -o "StrictHostKeyChecking no" -fNT -L ${PORT}:${IP}:${PORT} circleci@${PROXY_IP}
      - run:
          name: "Run tests and collect coverage reports"
          command: |
            go mod vendor
            go test ./... -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
            mv c.out /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - codecov/upload:
          file: /tmp/artifacts/*