version: 2.0

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    environment:
      PROXY_PRIVATE_KEY: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEeFlpRFRCVTFKYTFtSTdEQW4vV1JJcXMybnJiM3N3dE9YNE1YWi8vWTNTUUFBQUppUExxMmlqeTZ0Cm9nQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRHhZaURUQlUxSmExbUk3REFuL1dSSXFzMm5yYjNzd3RPWDRNWFovL1kzU1EKQUFBRUF1QS96UDRDeVJ5RGpoOEVJaGVZSThjYmQyYmI5TlZpV2NDa2N0dVZSWEx2RmlJTk1GVFVscldZanNNQ2Y5WkVpcQp6YWV0dmV6QzA1Zmd4ZG4vOWpkSkFBQUFFMk5wY21Oc1pXTnBRSFJ0WXpJMGNISnZlSGtCQWc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
      PROXY_PUBLIC_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPFiINMFTUlrWYjsMCf9ZEiqzaetvezC05fgxdn/9jdJ circleci@tmc24proxy
      PROXY_IP: 195.201.123.78
      CLIENT_ID: 2285
      ENV: GRU
      PORT: 34323
      IP: 127.0.0.1
      IP_REMOTE: 193.104.87.251
      MAX_CONNECTIONS: 11
      CLIENT_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCYz67v7DaR0dtVg+A3DtZ+F/hs\n5UgySayYdJeX9LrBmqBygr1i1l0u3e4+QtEa3ug29JOQKfbx2B2i8WscwrovyO7w\n4fLmtcYKr9n7Wmt8JFJYLFgxY1DbxaeKSCKsj0BW91EEt8wI2j9tuuvWqFNLUGfw\nvV76PtFSCGeCiU/EOQIDAQAB\n-----END PUBLIC KEY-----
      CLIENT_PRIVATE_KEY: -----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQCYz67v7DaR0dtVg+A3DtZ+F/hs5UgySayYdJeX9LrBmqBygr1i\n1l0u3e4+QtEa3ug29JOQKfbx2B2i8WscwrovyO7w4fLmtcYKr9n7Wmt8JFJYLFgx\nY1DbxaeKSCKsj0BW91EEt8wI2j9tuuvWqFNLUGfwvV76PtFSCGeCiU/EOQIDAQAB\nAoGABEdUY51ejcitdoCBx6jfspojN5FX6yiK753cHMIadI9KzMoCWYEdDNHj+NRQ\nHIt/PwKsGw5BvtXJRqWx1RVStza52/UdigA4/o0Xzv/yULt6SC+oWhzKbJ0eGtQS\nN32ontgVAl6e5YK8lq3EdGQ6JfVMg6C/cxk9srjoaEgmKjECQQDKYyOhQ0NpUHz3\n+HwLmxb+6PP4T4flCuRDuq/0iisZcw9SOSa6ZcQIirIOBwl9nBY3bTujLJlWwifu\nOFkmqo+FAkEAwUqOMqp1tlj8VlBBQqH7tK+cktNDEsatfesvroy1YAXZwLyQnRnM\nnPUg6N0+6VmSFoqxBR66p36jQGRJ0DzOJQJBAKTDtTwSMI1Kc5LE/ufL6Rq5t/UN\nekrjZRYmpBznZ1Mesvhzgq35L3DsySxWWkmiiwuwp/6dznAtPKjZwuqRrKkCQATj\nFq9PQgSnQVIJW20M3WlXG1VXBBYgcdiCLsVyB0/zNes6mUlvko3RYNCib2nE+v2Y\n6hrgCQYdHJGPN5KNRwUCQD06H/B1CDlq5azq/2ZgSSwkCe4mQG66SoAy8okVLZjW\nr8/LQeu6sjfOTciTWgxIo+gTppX7M4rdkYBHAqLtVhw=\n-----END RSA PRIVATE KEY-----
      CLIENT_PRIVATE_KEY_PASSWORD: ""
      SERVER_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDEqH2bjvfS8pEUxgbrpWVOiDOP\nyqwSju+CkYXT7+WpLTYhkdy5sCFy/b9XH48lmB7w8pY62B5AJ7Yg38nLDwEYw9yL\niae6WDAvJE9X4/mY0rRGMi9tBlK9TDA+51pZ619jg3paBT8YeGaKfguDTX+6FqB9\nYa9y4c56YQhoWGo6hwIDAQAB\n-----END PUBLIC KEY-----
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: "Create directories"
          command: |
            mkdir -p /tmp/artifacts
            mkdir -p ~/.ssh
      - run:
          name: "Config ssh port forwarding"
          command: |
            echo ${PROXY_PRIVATE_KEY} | base64 --decode > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/*
            ssh-keyscan -H ${PROXY_IP} >> ~/.ssh/known_hosts
            ssh -4 -fNT -L ${IP}:${PORT}:${IP_REMOTE}:${PORT} circleci@${PROXY_IP}
      - run:
          name: "Run tests and collect coverage reports"
          command: |
            make deps
            make test
            mv coverage.html /tmp/artifacts
            mv c.out /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Upload Coverage Results
          command: "bash <(curl -s https://codecov.io/bash) \
            -f /tmp/artifacts/* \
            -n ${CIRCLE_BUILD_NUM} \
            -t ${CODECOV_TOKEN} \
            -y .codecov.yml"
