version: 2

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: check content
          command: |
            ls -la
      - run:
          name: Run docker containe for test
          command: |
            docker run --device=/dev/net/tun \
              -v "$(pwd)":/home/circleci/project \
              circleci/golang:1.12 \
            ./.circleci/test.sh
      - store_artifacts:
          path: ./artifacts
      - run:
          command: |
            bash <(curl -s https://codecov.io/bash)